name: NysxlServerUtils
version: 1.0
main: org.Nysxl.NysxlServerUtils
description: A plugin that allows players to request access to commands they can't use.
api-version: 1.20
softdepend:
  - PlaceholderAPI
  - Vault